
CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.orders_ext_stage 
    URL = 's3://snowflakebucket-copyoption/returnfailed/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

    list @OUR_FIRST_DB.PUBLIC.orders_ext_stage ;

    CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_v10 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

    COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_v10  
 FROM @OUR_FIRST_DB.PUBLIC.orders_ext_stage 
 VALIDATION_mODE=RETURN_ERRORS;



 CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.order_ext_stage 
    URL = 's3://snowflakebucket-copyoption/returnfailed/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

    list @OUR_FIRST_DB.PUBLIC.order_ext_stage ;
     
     CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDER_v10 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

    
 COPY INTO OUR_FIRST_DB.PUBLIC.ORDER_v10  
 FROM @OUR_FIRST_DB.PUBLIC.order_ext_stage 
 VALIDATION_mODE=RETURN_ERRORS;
 SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDER_v10 ;
  DELETE FROM OUR_FIRST_DB.PUBLIC.ORDERS_v10 ;


    COPY INTO OUR_FIRST_DB.PUBLIC.ORDER_v10  
 FROM @OUR_FIRST_DB.PUBLIC.order_ext_stage 
ON_ERROR = CONTINUE
FORCE = TRUE;
 
 copy into OUR_FIRST_DB.PUBLIC.ORDERS_V3
    from @OUR_FIRST_DB.PUBLIC.orders_ext_stage 
    VALIDATION_MODE = RETURN_5_ROWS ;


    SELECT STATUS FROM OUR_FIRST_DB.PUBLIC.ORDER_ERROR;





    
    
    url = 's3://snowflakeparquetde


 CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.order_ext_stage 
    URL =// 's3://snowflakeparquetde'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);



    CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.
    URL = 's3://snowflakeparquetdemo'  
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);





    CREATE DATABASE VARIANT
    CREATE SCHEMA 









CREATE OR REPLACE stage VARIANT.PUBLIC.PARQUET_STAGE
     url= 's3://snowflakeparquetdemo'  
     FILE_FORMAT = (TYPE = PARQUET);

LIST @VARIANT.PUBLIC.PARQUET_STAGE;

CREATE OR REPLACE TABLE VARIANT.PUBLIC.PARQUET_DATA AS
SELECT * FROM @VARIANT.PUBLIC.PARQUET_STAGE;
