CREATE OR REPLACE stage OUR_FIRST_DB.EXTERNAL_STAGES.PARQUET
     url= 's3://snowflakeparquetdemo'  
     FILE_FORMAT = (TYPE ='PARQUET') 

     LIST@OUR_FIRST_DB.EXTERNAL_STAGES.PARQUET

     
CREATE OR REPLACE  TABLE   OUR_FIRST_DB.PUBLIC.PARQUET  ( PAR_DATA   VARIANT )

SELECT * FROM  OUR_FIRST_DB.PUBLIC.PARQUET;


COPY INTO  OUR_FIRST_DB.PUBLIC.PARQUET
FROM @OUR_FIRST_DB.EXTERNAL_STAGES.PARQUET;


-- Transformation 1: Total sales by category
SELECT
    PAR_DATA:cat_id::STRING AS category,
    SUM(PAR_DATA:value::INT) AS total_sales,
    COUNT(*) AS total_transactions
FROM OUR_FIRST_DB.PUBLIC.PARQUET
GROUP BY category;

-- Transformation 2: Sales by state and store
SELECT
    PAR_DATA:state_id::STRING AS state,
    PAR_DATA:store_id::STRING AS store,
    SUM(PAR_DATA:value::INT) AS total_sales,
    AVG(PAR_DATA:value::INT) AS avg_sales
FROM OUR_FIRST_DB.PUBLIC.PARQUET
GROUP BY state, store
ORDER BY total_sales DESC;

-- Transformation 3: Daily sales trend
SELECT
    TO_DATE(TO_TIMESTAMP_NTZ(PAR_DATA:date::BIGINT / 1000000)) AS sale_date,
    SUM(PAR_DATA:value::INT) AS daily_sales,
    COUNT(DISTINCT PAR_DATA:item_id::STRING) AS unique_items_sold
FROM OUR_FIRST_DB.PUBLIC.PARQUET
GROUP BY sale_date
ORDER BY sale_date;

-- Transformation 4: Top selling items per department
SELECT
    PAR_DATA:dept_id::STRING AS department,
    PAR_DATA:item_id::STRING AS item,
    SUM(PAR_DATA:value::INT) AS total_sales
FROM OUR_FIRST_DB.PUBLIC.PARQUET
GROUP BY department, item
QUALIFY ROW_NUMBER() OVER (PARTITION BY department ORDER BY total_sales DESC) <= 5
ORDER BY department, total_sales DESC;

-- Transformation 5: State-wise category performance (% contribution)
SELECT
    PAR_DATA:state_id::STRING AS state,
    PAR_DATA:cat_id::STRING AS category,
    SUM(PAR_DATA:value::INT) AS total_sales,
    ROUND(SUM(PAR_DATA:value::INT) * 100.0 / SUM(SUM(PAR_DATA:value::INT)) OVER (PARTITION BY PAR_DATA:state_id::STRING), 2) AS pct_of_state_sales
FROM OUR_FIRST_DB.PUBLIC.PARQUET
GROUP BY state, category
ORDER BY state, total_sales DESC;

CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.LOAN_STAGE
    URL = 's3://bucketsnowflakes3/Loan_payments_data.csv';

CREATE OR REPLACE FILE FORMAT OUR_FIRST_DB.PUBLIC.CSV_INFER
    TYPE = CSV
    PARSE_HEADER = TRUE;

SELECT * FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@OUR_FIRST_DB.PUBLIC.LOAN_STAGE',
        FILE_FORMAT => 'OUR_FIRST_DB.PUBLIC.CSV_INFER'
    )
);

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.LOAN_PAYMENTS
    USING TEMPLATE (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
        FROM TABLE(
            INFER_SCHEMA(
                LOCATION => '@OUR_FIRST_DB.PUBLIC.LOAN_STAGE',
                FILE_FORMAT => 'OUR_FIRST_DB.PUBLIC.CSV_INFER'
            )
        )
    );

COPY INTO OUR_FIRST_DB.PUBLIC.LOAN_PAYMENTS
FROM @OUR_FIRST_DB.PUBLIC.LOAN_STAGE
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT(*) FROM OUR_FIRST_DB.PUBLIC.LOAN_PAYMENTS;
-- Step 1: Create stage pointing to S3 (you only know the URL)
CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.LOAN_STAGE
    URL = 's3://bucketsnowflakes3/Loan_payments_data.csv';

-- Step 2: Create file format with PARSE_HEADER for CSV
CREATE OR REPLACE FILE FORMAT OUR_FIRST_DB.PUBLIC.CSV_INFER
    TYPE = CSV
    PARSE_HEADER = TRUE;

-- Step 3: Preview the inferred schema
SELECT * FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@OUR_FIRST_DB.PUBLIC.LOAN_STAGE',
        FILE_FORMAT => 'OUR_FIRST_DB.PUBLIC.CSV_INFER'
    )
);

-- Step 4: Auto-create table using USING TEMPLATE (no manual column definitions!)
CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.LOAN_PAYMENTS
    USING TEMPLATE (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
        FROM TABLE(
            INFER_SCHEMA(
                LOCATION => '@OUR_FIRST_DB.PUBLIC.LOAN_STAGE',
                FILE_FORMAT => 'OUR_FIRST_DB.PUBLIC.CSV_INFER'
            )
        )
    );

-- Step 5: Load data
COPY INTO OUR_FIRST_DB.PUBLIC.LOAN_PAYMENTS
FROM @OUR_FIRST_DB.PUBLIC.LOAN_STAGE
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;



CREATE OR REPLACE STAGE OUR_FIRST_DB.EXTERNAL_STAGES.LOAN_STAGE
    URL='s3://bucketsnowflakes3/Loan_payments_data.csv'
    FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1);


CREATE OR REPLACE FILE FORMAT OUR_FIRST_DB.EXTERNAL_STAGES.CSV_INFER_FORMAT
    TYPE=CSV
    PARSE_HEADER=TRUE;


SELECT *
FROM TABLE(
    INFER_SCHEMA(
        LOCATION=>'@OUR_FIRST_DB.EXTERNAL_STAGES.LOAN_STAGE',
        FILE_FORMAT=>'OUR_FIRST_DB.EXTERNAL_STAGES.CSV_INFER_FORMAT'
    )
);


CREATE OR REPLACE TABLE OUR_FIRST_DB.EXTERNAL_STAGES.LOAN_PAYMENTS
    USING TEMPLATE (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
        FROM TABLE(
            INFER_SCHEMA(
                LOCATION=>'@OUR_FIRST_DB.EXTERNAL_STAGES.LOAN_STAGE',
                FILE_FORMAT=>'OUR_FIRST_DB.EXTERNAL_STAGES.CSV_INFER_FORMAT'
            )
        )
    );


COPY INTO OUR_FIRST_DB.EXTERNAL_STAGES.LOAN_PAYMENTS
    FROM @OUR_FIRST_DB.EXTERNAL_STAGES.LOAN_STAGE
    FILE_FORMAT=(TYPE=CSV PARSE_HEADER=TRUE)
    MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;

SELECT COUNT(*) FROM OUR_FIRST_DB.EXTERNAL_STAGES.LOAN_PAYMENTS;

SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT JOB_ID, COUNT(*) AS TOTAL_EMPLOYEES
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY JOB_ID;

SELECT DEPARTMENT_ID, SUM(SALARY) AS TOTAL_SALARY
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MAX(SALARY) AS MAX_SALARY
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT JOB_ID, SUM(SALARY) AS TOTAL_SALARY
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY JOB_ID;

SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 3;

SELECT JOB_ID, SUM(SALARY) AS TOTAL_SALARY
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY JOB_ID
HAVING SUM(SALARY) > 40000;

SELECT JOB_ID, COUNT(*) AS TOTAL_EMPLOYEES
FROM VITECH.PUBLIC.EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(*) > 3;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM VITECH.PUBLIC.EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM VITECH.PUBLIC.EMPLOYEES);

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.JOBS J ON E.JOB_ID = J.JOB_ID
WHERE J.JOB_TITLE ILIKE '%clerk%'
AND E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM VITECH.PUBLIC.EMPLOYEES E2
    JOIN VITECH.PUBLIC.JOBS J2 ON E2.JOB_ID = J2.JOB_ID
    WHERE J2.JOB_TITLE ILIKE '%clerk%'
);

-- 53) Display names of salesman (Sales dept) earning more than highest salary of any clerk
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Sales'
AND E.SALARY > (
    SELECT MAX(E2.SALARY)
    FROM VITECH.PUBLIC.EMPLOYEES E2
    JOIN VITECH.PUBLIC.JOBS J ON E2.JOB_ID = J.JOB_ID
    WHERE J.JOB_TITLE ILIKE '%clerk%'
);

-- 54) Display names of clerks earning more than lowest salary of any salesman (Sales dept)
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.JOBS J ON E.JOB_ID = J.JOB_ID
WHERE J.JOB_TITLE ILIKE '%clerk%'
AND E.SALARY > (
    SELECT MIN(E2.SALARY)
    FROM VITECH.PUBLIC.EMPLOYEES E2
    JOIN VITECH.PUBLIC.DEPARTMENTS D ON E2.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE D.DEPARTMENT_NAME = 'Sales'
);

-- Display employees earning more than Jones or more than Scott
-- Note: No employees named Jones or Scott exist in this dataset
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM VITECH.PUBLIC.EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM VITECH.PUBLIC.EMPLOYEES WHERE LAST_NAME = 'Jones')
OR SALARY > (SELECT SALARY FROM VITECH.PUBLIC.EMPLOYEES WHERE LAST_NAME = 'Scott');

-- 55) Display employees who earn highest salary in their respective departments
SELECT E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
WHERE E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM VITECH.PUBLIC.EMPLOYEES E2
    WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
);

-- 56) Display employees who earn highest salary in their respective job groups
SELECT E.FIRST_NAME, E.LAST_NAME, E.JOB_ID, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
WHERE E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM VITECH.PUBLIC.EMPLOYEES E2
    WHERE E2.JOB_ID = E.JOB_ID
);

-- 57) Display employee names working in accounting department
SELECT E.FIRST_NAME, E.LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Accounting';

-- 58) Display employee names working in Chicago
-- Note: No department is located in Chicago in this dataset
SELECT E.FIRST_NAME, E.LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN VITECH.PUBLIC.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = 'Chicago';

-- 59) Display job groups having total salary greater than max salary for managers
SELECT J.JOB_TITLE, SUM(E.SALARY) AS TOTAL_SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING SUM(E.SALARY) > (
    SELECT MAX(E2.SALARY)
    FROM VITECH.PUBLIC.EMPLOYEES E2
    JOIN VITECH.PUBLIC.JOBS J2 ON E2.JOB_ID = J2.JOB_ID
    WHERE J2.JOB_TITLE ILIKE '%manager%'
);

-- 60) Display employees from department 10 with salary greater than any employee in other departments
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
WHERE E.DEPARTMENT_ID = 10
AND E.SALARY > ANY (
    SELECT SALARY
    FROM VITECH.PUBLIC.EMPLOYEES
    WHERE DEPARTMENT_ID != 10
);

-- 61) Display employees from department 10 with salary greater than ALL employees in other departments
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM VITECH.PUBLIC.EMPLOYEES
WHERE DEPARTMENT_ID = 10
AND SALARY > ALL (
    SELECT SALARY
    FROM VITECH.PUBLIC.EMPLOYEES
    WHERE DEPARTMENT_ID != 10
);

-- 62) Display employee names in UPPERCASE
SELECT UPPER(FIRST_NAME) AS FIRST_NAME, UPPER(LAST_NAME) AS LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES;

-- 63) Display employee names in lowercase
SELECT LOWER(FIRST_NAME) AS FIRST_NAME, LOWER(LAST_NAME) AS LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES;

-- 64) Display employee names in Propercase
SELECT INITCAP(FIRST_NAME) AS FIRST_NAME, INITCAP(LAST_NAME) AS LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES;

-- 65) Display the length of your name using appropriate function
SELECT LENGTH('KALPANA') AS NAME_LENGTH;

-- 66) Display the length of all employee names
SELECT FIRST_NAME, LAST_NAME, LENGTH(FIRST_NAME) AS FIRST_NAME_LENGTH, LENGTH(LAST_NAME) AS LAST_NAME_LENGTH
FROM VITECH.PUBLIC.EMPLOYEES;

-- 67) Select name of employee concatenated with employee number
SELECT FIRST_NAME || ' ' || CAST(EMPLOYEE_ID AS VARCHAR) AS NAME_WITH_NUMBER
FROM VITECH.PUBLIC.EMPLOYEES;

-- 68) Extract 3 characters starting from 2nd character from 'Oracle'
SELECT SUBSTR('Oracle', 2, 3) AS RESULT;

-- 69) Find first occurrence of character 'a' in 'Computer Maintenance Corporation'
SELECT POSITION('a' IN 'Computer Maintenance Corporation') AS FIRST_OCCURRENCE;

-- 70) Replace every occurrence of A with B in 'Allens' using TRANSLATE
SELECT TRANSLATE('Allens', 'Aa', 'Bb') AS RESULT;

-- 71) Display info from emp table, where job 'Manager' is replaced with 'Boss'
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,
       REPLACE(J.JOB_TITLE, 'Manager', 'Boss') AS JOB_TITLE, SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.JOBS J ON E.JOB_ID = J.JOB_ID;

-- 72) Display empno, ename, deptno with department name using DECODE
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,
       DECODE(DEPARTMENT_ID,
           1, 'Administration',
           2, 'Marketing',
           3, 'Purchasing',
           4, 'Human Resources',
           5, 'Shipping',
           6, 'IT',
           7, 'Public Relations',
           8, 'Sales',
           9, 'Executive',
           10, 'Finance',
           11, 'Accounting',
           'Unknown') AS DEPARTMENT_NAME
FROM VITECH.PUBLIC.EMPLOYEES;

-- 73) Display your age in days
SELECT DATEDIFF('DAY', '1990-01-01'::DATE, CURRENT_DATE()) AS AGE_IN_DAYS;

-- 74) Display your age in months
SELECT DATEDIFF('MONTH', '1990-01-01'::DATE, CURRENT_DATE()) AS AGE_IN_MONTHS;

-- 75) Display the current date in long format
SELECT TO_CHAR(CURRENT_DATE(), 'DDth Month Day YYYY') AS FORMATTED_DATE;

-- 76) Display employee join info in sentence format
SELECT FIRST_NAME || ' has joined the company on ' ||
       DAYNAME(HIRE_DATE) || ' ' ||
       TO_CHAR(HIRE_DATE, 'DDth Month YYYY') AS JOIN_INFO
FROM VITECH.PUBLIC.EMPLOYEES;

-- 77) Find the date for nearest Saturday after current date
SELECT NEXT_DAY(CURRENT_DATE(), 'SA') AS NEXT_SATURDAY;

-- 78) Display current time
SELECT CURRENT_TIMESTAMP() AS CURRENT_TIME;

-- 79) Display the date three months before the current date
SELECT DATEADD('MONTH', -3, CURRENT_DATE()) AS THREE_MONTHS_BEFORE;

-- 80) Display common jobs from department number 10 and 20
SELECT DISTINCT JOB_ID
FROM VITECH.PUBLIC.EMPLOYEES
WHERE DEPARTMENT_ID = 10
INTERSECT
SELECT DISTINCT JOB_ID
FROM VITECH.PUBLIC.EMPLOYEES
WHERE DEPARTMENT_ID = 20;

-- 81) Display jobs found in department 10 and 20, eliminate duplicates
SELECT JOB_ID FROM VITECH.PUBLIC.EMPLOYEES WHERE DEPARTMENT_ID = 10
UNION
SELECT JOB_ID FROM VITECH.PUBLIC.EMPLOYEES WHERE DEPARTMENT_ID = 20;

-- 82) Display jobs which are unique to department 10
SELECT JOB_ID FROM VITECH.PUBLIC.EMPLOYEES WHERE DEPARTMENT_ID = 10
EXCEPT
SELECT JOB_ID FROM VITECH.PUBLIC.EMPLOYEES WHERE DEPARTMENT_ID != 10;

-- 84) Display employees in sales department and grade 3
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Sales';

-- 85i) Display the managers names
SELECT DISTINCT M.FIRST_NAME, M.LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID;

-- 85ii) Display employees who are not managers
SELECT E.FIRST_NAME, E.LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
WHERE E.EMPLOYEE_ID NOT IN (
    SELECT DISTINCT MANAGER_ID FROM VITECH.PUBLIC.EMPLOYEES WHERE MANAGER_ID IS NOT NULL
);

-- 86) Display employees whose name contains not less than 4 characters
SELECT FIRST_NAME, LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES
WHERE LENGTH(FIRST_NAME) >= 4;

-- 87) Display departments whose name starts with 'S' and location ends with 'K'
SELECT D.DEPARTMENT_NAME, L.CITY
FROM VITECH.PUBLIC.DEPARTMENTS D
JOIN VITECH.PUBLIC.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE D.DEPARTMENT_NAME LIKE 'S%'
AND L.CITY LIKE '%k';

-- 88) Display employees whose manager name is JONES
SELECT E.FIRST_NAME, E.LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE M.LAST_NAME = 'Jones';

-- 89) Display employees whose salary is more than 3000 after giving 20% increment
SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY * 1.20 AS INCREMENTED_SALARY
FROM VITECH.PUBLIC.EMPLOYEES
WHERE SALARY * 1.20 > 3000;

-- 90) Display all employees with their department names
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 91) Display employees working in sales dept
SELECT E.FIRST_NAME, E.LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Sales';

-- 92) Display employee name, dept name, salary for sal between 2000-5000, location Chicago
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN VITECH.PUBLIC.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.SALARY BETWEEN 2000 AND 5000
AND L.CITY = 'Chicago';

-- 93) Display employees whose salary is greater than their manager's salary
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, M.FIRST_NAME AS MGR_NAME, M.SALARY AS MGR_SALARY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.SALARY > M.SALARY;

-- 94) Display employees working in the same dept as their manager
SELECT E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.DEPARTMENT_ID = M.DEPARTMENT_ID;

-- 95) Display employees who are not working under any manager
SELECT FIRST_NAME, LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- 96) Display employee name for dept 10 or 30, joined before 31-Dec-82
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, HIRE_DATE
FROM VITECH.PUBLIC.EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 30)
AND HIRE_DATE < '1982-12-31';

-- 97) Update salary by 10% increment for employees not eligible for commission
UPDATE VITECH.PUBLIC.EMPLOYEES
SET SALARY = SALARY * 1.10
WHERE EMPLOYEE_ID NOT IN (
    SELECT EMPLOYEE_ID FROM VITECH.PUBLIC.EMPLOYEES WHERE SALARY IS NULL
);

-- 98) Display employees who joined before 31-Dec-82, location New York or Chicago
SELECT E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE, L.CITY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN VITECH.PUBLIC.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.HIRE_DATE < '1982-12-31'
AND L.CITY IN ('New York', 'Chicago');

-- 99) Display employee name, job, department, location for all working as manager
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.JOBS J ON E.JOB_ID = J.JOB_ID
JOIN VITECH.PUBLIC.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN VITECH.PUBLIC.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE J.JOB_TITLE ILIKE '%manager%';

-- 100) Display employees whose manager name is Jones and their manager name
SELECT E.FIRST_NAME, E.LAST_NAME, M.FIRST_NAME AS MGR_FIRST_NAME, M.LAST_NAME AS MGR_LAST_NAME
FROM VITECH.PUBLIC.EMPLOYEES E
JOIN VITECH.PUBLIC.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE M.LAST_NAME = 'Jones';

-- 101) Display name and salary of employee named Ford if salary equals max salary in their grade
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM VITECH.PUBLIC.EMPLOYEES
WHERE LAST_NAME = 'Ford'
AND SALARY = (SELECT MAX(SALARY) FROM VITECH.PUBLIC.EMPLOYEES);